fake_names = [
    "Annabel Downs",
    "Marquis Ritter",
    "Jan Estrada",
    "Izayah Gardner",
    "Catalina Suarez",
    "Marcelo Hubbard",
    "Jaidyn Spears",
    "Rayna Delgado",
    "Madilynn Berger",
    "Amiya Powell",
    "Neil Haney",
    "King Frank",
    "Kamden Carney",
    "Emily Butler",
    "Carmen Zhang",
    "Alyvia Macias",
    "Karina Bryant",
    "Jazlyn Bernard",
    "Abdiel Levine",
    "Kasen Rubio",
    "Trent Andrews",
    "Cynthia Black",
    "Brian Dalton",
    "Jazlynn Bauer",
    "Alyvia Cuevas",
    "Junior Carson",
    "Manuel Li",
    "Angie Riley",
    "Brianna Wells",
    "Leonard Ray",
    "Nyasia Mckee",
    "Kenyon Osborne",
    "Ivy Graham",
    "Jayvon Shea",
    "Kenzie West",
    "Alexis Pitts",
    "Francis Floyd",
    "Morgan Nichols",
    "Quintin Alexander",
    "Raelynn Mccullough"
]

fake_emails = [
    "mnemonic@me.com",
    "cremonini@msn.com",
    "rbarreira@att.net",
    "isorashi@comcast.net",
    "farber@yahoo.com",
    "mhanoh@att.net",
    "hachi@yahoo.com",
    "claesjac@mac.com",
    "zilla@comcast.net",
    "brainless@hotmail.com",
    "pplinux@aol.com",
    "tbeck@aol.com",
    "sinclair@aol.com",
    "jdray@aol.com",
    "dsugal@me.com",
    "telbij@yahoo.com",
    "onestab@msn.com",
    "dvdotnet@yahoo.com",
    "singh@comcast.net",
    "hampton@mac.com",
    "burniske@mac.com",
    "heckerman@live.com",
    "dobey@verizon.net",
    "smcnabb@optonline.net",
    "lukka@sbcglobal.net",
    "codex@verizon.net",
    "qrczak@aol.com",
    "ducasse@aol.com",
    "nasarius@sbcglobal.net",
    "yenya@aol.com",
    "roesch@yahoo.ca",
    "stefano@live.com",
    "ebassi@yahoo.com",
    "irving@gmail.com",
    "nichoj@gmail.com",
    "petersko@sbcglobal.net",
    "dieman@comcast.net",
    "fairbank@sbcglobal.net",
    "sethbrown@icloud.com",
    "dobey@msn.com",
]

bank_names = [
"Toronto-Dominion Bank.",
"Royal Bank of Canada.",
"Bank of Nova Scotia.",
"Bank of Montreal.",
"CIBC.",
"Desjardins Group.",
"National Bank.",
"HSBC Bank.",
]