"""
This file contains a list of fake data
"""
fake_names = [
    ["Annabel", "Downs"],
    ["Marquis", "Ritter"],
    ["Jan", "Estrada"],
    ["Izayah", "Gardner"],
    ["Catalina", "Suarez"],
    ["Marcelo", "Hubbard"],
    ["Jaidyn", "Spears"],
    ["Rayna", "Delgado"],
    ["Madilynn", "Berger"],
    ["Amiya", "Powell"],
    ["Neil", "Haney"],
    ["King", "Frank"],
    ["Kamden", "Carney"],
    ["Emily", "Butler"],
    ["Carmen", "Zhang"],
    ["Alyvia", "Macias"],
    ["Karina", "Bryant"],
    ["Jazlyn", "Bernard"],
    ["Abdiel", "Levine"],
    ["Kasen", "Rubio"],
    ["Trent", "Andrews"],
    ["Cynthia", "Black"],
    ["Brian", "Dalton"],
    ["Jazlynn", "Bauer"],
    ["Alyvia", "Cuevas"],
    ["Junior", "Carson"],
    ["Manuel", "Li"],
    ["Angie", "Riley"],
    ["Brianna", "Wells"],
    ["Leonard", "Ray"],
    ["Nyasia", "Mckee"],
    ["Kenyon", "Osborne"],
    ["Ivy", "Graham"],
    ["Jayvon", "Shea"],
    ["Kenzie", "West"],
    ["Alexis", "Pitts"],
    ["Francis", "Floyd"],
    ["Morgan", "Nichols"],
    ["Quintin", "Alexander"],
    ["Raelynn", "Mccullough"]
]

fake_emails = [
    "mnemonic@me.com",
    "cremonini@msn.com",
    "rbarreira@att.net",
    "isorashi@comcast.net",
    "farber@yahoo.com",
    "mhanoh@att.net",
    "hachi@yahoo.com",
    "claesjac@mac.com",
    "zilla@comcast.net",
    "brainless@hotmail.com",
    "pplinux@aol.com",
    "tbeck@aol.com",
    "sinclair@aol.com",
    "jdray@aol.com",
    "dsugal@me.com",
    "telbij@yahoo.com",
    "onestab@msn.com",
    "dvdotnet@yahoo.com",
    "singh@comcast.net",
    "hampton@mac.com",
    "burniske@mac.com",
    "heckerman@live.com",
    "dobey@verizon.net",
    "smcnabb@optonline.net",
    "lukka@sbcglobal.net",
    "codex@verizon.net",
    "qrczak@aol.com",
    "ducasse@aol.com",
    "nasarius@sbcglobal.net",
    "yenya@aol.com",
    "roesch@yahoo.ca",
    "stefano@live.com",
    "ebassi@yahoo.com",
    "irving@gmail.com",
    "nichoj@gmail.com",
    "petersko@sbcglobal.net",
    "dieman@comcast.net",
    "fairbank@sbcglobal.net",
    "sethbrown@icloud.com",
    "dobey@msn.com",
]

bank_names = [
    "Toronto-Dominion Bank.",
    "Royal Bank of Canada.",
    "Bank of Nova Scotia.",
    "Bank of Montreal.",
    "CIBC.",
    "Desjardins Group.",
    "National Bank.",
    "HSBC Bank.",
]

email_providers = [
    "gmail",
    "hotmail",
    "outlook",
    "yahoo"
]

bc_cities = [
    "VANCOUVER",
    "SURREY",
    "BURNABY",
    "RICHMOND",
    "COQUITLAM",
    "DELTA",
    "MAPLE RIDGE",
    "NEW WESTMINSTER",
    "PORT COQUITLAM",
    "PORT MOODY",

]

fake_street_names = [
    "Christopher Ridge",
    "Copley Place",
    "Carisbrooke Gate",
    "Carlisle Fold",
    "Carfin Drive",
    "Chase Brow",
    "Cameron Heights",
    "Cardigan Ridgeway",
    "Coopers Circus",
    "Culdrose Close",
]

debit_credit = [
    "debit",
    "credit"
]

visa_mastercard = [
    "visa",
    "mastercard"
]


restaurant_names = [
    "McDonald's",
    "Starbucks",
    "Chick-fil-A",
    "Taco Bell",
    "Wendy's",
    "Dunkin'",
    "Burger King",
    "Subway",
    "Domino's",
    "Chipotle Mexican Grill",
    "Sonic Drive-In",
    "Panera Bread",
    "Pizza Hut",
    "KFC",
    "Popeyes",
    "Panda Express",
    "Dairy Queen",
]

list_of_cuisine = [
    "American",
    "fast food",
    "Indian",
    "Japanese",
    "Asian",
    "European"
]

list_of_dishes = [
    "Shallow-Fried Basil & Lime Turkey",
    "Fried Honey Quail",
    "Pressure-Fried Mustard & Thyme Ostrich",
    "Seared Vinegar Yak",
    "Deep-Fried Carrot & Violet Pork",
    "Seared Stew of Mutton",
    "Oven-Baked Mint & Berry Pork",
    "Infused Salty & Sour Lamb",
    "Braised Fennel & Garlic Horse",
    "Tea-Smoked Mustard Pork",
    "Oven-Grilled Creamy Quail",
    "Dried Olives & Mustard Rabbit",
    "Deep-Fried Honey & Nuts Mammoth",
    "Oven-Baked Red Whine Ostrich",
    "Shallow-Fried Basil & Lime Turkey",
    "Stir-Fried Garlic & Lime Lamb",
    "Simmered Soy Quail",
    "Shallow-Fried Garlic & Rosemary Beef",
    "Pressure-Cooked Ginger & Honey Yak",
    "Baked Garlic & Lime Beef",
    "Grilled Truffles & Boar",
    "Braised Sour Mutton",
    "Dried Salt & Savory Yak",
    "Stir-Fried Apples & Walnut Venison",
    "Gentle-Fried Light Beer Chicken",
    "Basted Blueberry Pork",
    "Engine-Cooked Garlic & Tomato Quail",
    "Engine-Cooked Raspberry & Peanut Beef",
    "Roasted Honey-Coated Mutton",
    "Pan-Fried Oregano Pheasant",
    "Cured Curry of Mammoth",
    "Pressure-Fried Confit of Bear",
    "Simmered Soy Quail",
    "Marinated Mint & Orange Venison",
    "Tenderized Dark Beer Mammoth",
    "Pan-Fried Apricots & Honey Chicken",
    "Baked Curry of Mutton",
    "Cooked Cocoa & Mushroom Mammoth",
    "Cooked Salty & Sour Ostrich",
    "Stewed Paprika Yak",
    "Shallow-Fried Parsnip & Pear Mammoth",
    "Stuffed Curry of Chicken",
    "Fire-Grilled Parsnip & Pear Beef",
    "Poached Cranberry Venison",
    "Marinated Watercress Yak",
    "Oven-Grilled Mushroom & Rosemary Mammoth",
    "Infused Salty & Sour Lamb",
    "Gentle-Fried Fennel & Orange Boar",
    "Dried Beets & Orange Rabbit",
    "Pickled Parsnip & Pear Beef",
    "Seared Saffron & Shallot Pheasant",
    "Fire-Roasted Wasabi Bear",
    "Tea-Smoked Salt & Savory Rabbit",
    "Dry-Roasted Ginger & Honey Pork",
    "Barbecued Mint & Mustard Beef",
    "Steamed Apple & Lavender Pheasant",
    "Broasted White Wine Lamb",
    "Deep-Fried Apple & Lavender Pheasant",
    "Engine-Cooked Raspberry & Peanut Beef",
    "Dry-Roasted Parsnip & Pear Mutton",
    "Shallow-Fried Egg & Beet Yak",
    "Basted Blackberry & Ginger Mammoth",
    "Breaded Fennel & Lemon Turkey",
    "Pressure-Cooked Vanilla Pigeon",
    "Roasted Peppermint Turkey",
    "Fire-Grilled Thyme & Parsley Ostrich",
    "Pickled Pepper & Lime Yak",
    "Thermal-Cooked Chestnuts & Bear",
    "Simmered Pepper & Garlic Rabbit",
    "Marinated Onions & Cream Quail",
    "Fried Sweet & Fresh Beef",
    "Oven-Grilled Cinnamon & Thyme Pheasant",
    "Basted Blueberry Pork",
    "Dried Fennel & Lemon Pork",
    "Shallow-Fried Mint Mutton",
    "Engine-Cooked Honey & Almond Chicken ",
]
